package com.geekbrains.core.model;

public enum CommandType {

    FILE_MESSAGE,
    SERVER_FILE_UPLOAD_RESPONSE,
    UPDATE_LIST_SERVER_REQUEST,
    UPDATE_LIST_SERVER_RESPONSE,
    SEND_AUTH_TO_SERVER,
    AUTH_OK,
    REGISTRATION_TO_SERVER,
    REGISTRATION_OK,
    SERVER_FILE_DOWNLOAD_REQUEST,
    SERVER_FILE_DELETE_REQUEST
}
